### ISSUE TITLE
I18n: Changes made on Vue Theme about aria announce 

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/docs-ja#919]
Hi,

Just to let you know that I fix a typo on a type which could made regression on your translated Vue docs.

https://github.com/vuejs/theme/issues/75

<s>I encourage you to use the i18nConfig type to avoid any surprises in the future.

Also, it seems that the skipTheContent field is not well used in your config.</s>

**Comment by jay-es** [comment]
@edimitchel Thank you!
I'll fix `config.ts` when `@vue/theme` is updated.

**Comment by jay-es** [comment]
`.vitepress/config.ts`
```diff
-  ariaAnnouner: {
+  ariaAnnouncer: {
```

**Comment by kazupon** [comment]
What status is this issue? 🤔 
Can we close this issue?

**Comment by edimitchel** [comment]
Still visible on the main branch, so still an issue for `docs-ja`.

**Comment by jay-es** [comment]
Fixing this typo causes a type error. Because the latest version of `@vue/theme` still has typo "ariaAnnouner".
So, I'm waiting for updating of `@vue/theme`.

Should I add a comment and close this issue like `zh-cn`?
https://github.com/vuejs-translations/docs-zh-cn/blob/main/.vitepress/config.ts#L578-L580

**Comment by kazupon** [comment]
Thanks guys!

@jay-es 
We should ping in the comments. we're not in hurry, but this issue is blocked. :)
